"""Closed preference taxonomy copied from the preference-model repository.

Keeping the names local makes this folder independent from the training repo,
while preserving the exact signal names expected by the trainable retrieval
block.
"""

VALID_LABELS = {"do_now", "do_later", "remind", "no_action"}

PREFERENCE_SIGNALS = {
    "prefer_formal_tone",
    "prefer_friendly_tone",
    "prefer_brief_messages",
    "prefer_detailed_messages",
    "prefer_confirmation_before_action",
    "prefer_no_confirmation_for_low_risk",
    "prefer_voice_interaction",
    "prefer_text_interaction",
    "prefer_high_robot_autonomy",
    "prefer_shared_control",
    "prefer_user_final_decision",
    "prefer_manual_override_always",
    "prefer_morning_tasks",
    "prefer_afternoon_tasks",
    "prefer_evening_tasks",
    "avoid_interrupt_during_quiet_hours",
    "prefer_strict_routine",
    "prefer_flexible_routine",
    "prefer_proactive_reminders",
    "prefer_on_demand_reminders",
    "prefer_immediate_safety_intervention",
    "prefer_notify_before_safety_intervention",
    "prefer_conservative_risk_policy",
    "prefer_fast_action_under_risk",
    "prefer_minimal_data_logging",
    "prefer_full_activity_logging",
    "prefer_local_data_only",
    "prefer_family_data_sharing",
    "prefer_no_third_party_sharing",
    "prefer_step_by_step_guidance",
    "prefer_do_it_for_me",
    "prefer_coaching_not_execution",
    "prefer_non_intrusive_assistance",
    "prefer_proactive_assistance",
    "prefer_medication_support",
    "prefer_meal_support",
    "prefer_housekeeping_support",
    "prefer_mobility_support",
    "prefer_social_activity_support",
    "prefer_cognitive_training_support",
    "avoid_assistance_when_guests_present",
    "prefer_assistance_when_user_busy",
    "avoid_assistance_when_user_stressed",
    "prefer_assistance_in_specific_rooms",
    "avoid_nighttime_notifications",
    "prefer_explain_why_decision",
    "prefer_explain_alternatives",
    "prefer_no_explanation",
    "prefer_feedback_request_after_action",
}

DOMAIN_KEYWORDS = {
    "prefer_medication_support": {
        "medication",
        "medicine",
        "pill",
        "tablet",
        "health",
    },
    "prefer_meal_support": {
        "meal",
        "food",
        "breakfast",
        "lunch",
        "dinner",
        "kitchen",
        "mug",
        "bowl",
        "plate",
        "banana",
        "strawberry",
        "orange",
        "pudding",
        "spoon",
        "fork",
        "cook",
        "cooking",
    },
    "prefer_housekeeping_support": {
        "clean",
        "cleaning",
        "tidy",
        "laundry",
        "washing",
        "counter",
        "countertop",
        "cloth",
        "organize",
        "arrange",
        "place",
        "put",
        "move",
    },
    "prefer_mobility_support": {
        "walk",
        "walking",
        "mobility",
        "exercise",
        "stairs",
        "stretch",
    },
    "prefer_social_activity_support": {
        "friend",
        "family",
        "social",
        "conversation",
        "visit",
        "call",
        "guest",
        "guests",
    },
    "prefer_cognitive_training_support": {
        "read",
        "reading",
        "book",
        "puzzle",
        "memory",
        "game",
        "creative",
        "planning",
        "idea",
        "sketch",
    },
}

